VERSION = "0.0.0"

local config = import("micro/config")

config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-citrus-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-colorful-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-forest-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-frog-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-frozen-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-latte-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-lava-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-lavender-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-mint-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-moss-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-neon-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-RGB-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-salt-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-sapphire-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-sea-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-waffle-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-warm-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/burixon-wine-dark.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/kareha-16.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/kareha.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/mtp.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/nord-16-light.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/nord-16.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/nord-tc-light.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/nord-tc.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/photon-racer.micro")
config.AddRuntimeFile("pubcolors", config.RTColorscheme, "colorschemes/bluemood-tc.micro")

function init()
	config.AddRuntimeFile("pubcolors", config.RTHelp, "help/pubcolors.md")
end
